### ISSUE TITLE
Panic after failing to create a consumer group in kafka consumer

### ISSUE THREAD

**Issue by Oberonus** [beatlabs/patron#250]
## Is your feature request related to a problem? Please describe

- When patron fails to create a new consumer in `Consume()` -- `cg, err := sarama.NewConsumerGroup(c.config.Brokers, c.group, c.config.SaramaConfig)` it returns an error and leaves internal `c.cg` with `nil` value.   (in `component/async/kafka/group/group.go`)
- After this in `component/async/component.go` it returns with error and defer function is being called.
- In deferred function there is a call to `Close()` consumer method.
- `Close()` method in `component/async/kafka/group/group.go` calls `c.cg.Close()` on nil value and resulting with panic `runtime error: invalid memory address or nil pointer dereference`

## Is this a bug? Please provide steps to reproduce, a failing test etc.

It is a bug. Stack trace (for patron v0.40.1):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc8dcbb]

goroutine 75 [running]:
github.com/beatlabs/patron/component/async/kafka/group.(*consumer).Close(0xc00104ee10, 0xc000992460, 0x92)
	/go/sonar/vendor/github.com/beatlabs/patron/component/async/kafka/group/group.go:95 +0x3b
github.com/beatlabs/patron/component/async.(*Component).processing.func1(0x11762e0, 0xc00104ee10, 0xc003949e78)
	/go/sonar/vendor/github.com/beatlabs/patron/component/async/component.go:160 +0x35
github.com/beatlabs/patron/component/async.(*Component).processing(0xc0000d0b80, 0x1182760, 0xc000534000, 0x116c400, 0xc001c92e00)
	/go/sonar/vendor/github.com/beatlabs/patron/component/async/component.go:168 +0x2ce
github.com/beatlabs/patron/component/async.(*Component).Run(0xc0000d0b80, 0x1182760, 0xc000534000, 0x0, 0x0)
	/go/sonar/vendor/github.com/beatlabs/patron/component/async/component.go:136 +0x75
github.com/beatlabs/patron.(*service).run.func2(0xc00039b5e0, 0xc0003e8000, 0x1182760, 0xc000534000, 0x116cb60, 0xc0000d0b80)
	/go/sonar/vendor/github.com/beatlabs/patron/service.go:83 +0x77
created by github.com/beatlabs/patron.(*service).run
	/go/sonar/vendor/github.com/beatlabs/patron/service.go:81 +0x1a3
```

## Describe the solution

Add a check for confumer group `nil` value in `Close()` function.

**Comment by Oberonus** [comment]
False start, was fixed in https://github.com/beatlabs/patron/pull/208
