### ISSUE TITLE
examples/amqp/main.go panics and does not start

### ISSUE THREAD

**Issue by rbroggi** [beatlabs/patron#387]
## Is your feature request related to a problem? Please describe

In the examples folder, the service `examples/amqp/main.go` panics at consuming messages.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

run:

Start the dependencies
```bash
docker-compose up -d
```
Start the amp service
```bash
go run examples/http-cache/main.go &
go run examples/http/main.go &
go run examples/http-sec/main.go &
go run examples/kafka/main.go &
go run examples/amqp/main.go &
go run examples/sqs/main.go & 
go run examples/grpc/main.go & 
```
Output:
```
2021/06/05 10:01:27.902125 component.go:75: INF host=<my_host_name> srv=amqp ver=1.0.0 HTTP component listening on port 50003
2021/06/05 10:01:27.905472 component.go:277: INF host=<my_host_name> srv=amqp ver=1.0.0 consuming messages for tag 13b4e8e9-7c15-4fc1-8119-967e887289f3
2021/06/05 10:01:27.906250 component.go:221: DBG host=<my_host_name> srv=amqp ver=1.0.0 processing message 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaf7d97]

goroutine 98 [running]:
github.com/beatlabs/patron/client/sns/v2.Publisher.Publish(0xff59a0, 0xc0000102f8, 0xfdca20, 0xc00025aed0, 0xc0002aa4b0, 0x25, 0x0, 0xc0000d6000, 0xc000120000)
        <project_root_dir>/client/sns/v2/publisher.go:72 +0x247
main.(*amqpComponent).Process(0xc000304b40, 0xfdc960, 0xc00060e000, 0xfd9820, 0xc00000e260)
        <project_root_dir>/examples/amqp/main.go:266 +0x63c
github.com/beatlabs/patron/component/amqp.(*Component).processAndResetBatch(...)
        <project_root_dir>/component/amqp/component.go:318
github.com/beatlabs/patron/component/amqp.(*Component).processBatch(0xc0003d6000, 0xfdc960, 0xc00060e000, 0xc0000d6000, 0xc00000e260)
        <project_root_dir>/component/amqp/component.go:309 +0xb7
github.com/beatlabs/patron/component/amqp.(*Component).processLoop(0xc0003d6000, 0xfdc960, 0xc00060e000, 0xc0000d8000, 0xc0000bec60, 0xc00032e1e0, 0x0, 0x0, 0x0)
        <project_root_dir>/component/amqp/component.go:223 +0x44f
github.com/beatlabs/patron/component/amqp.(*Component).Run(0xc0003d6000, 0xfdc960, 0xc00060e000, 0x0, 0x0)
        <project_root_dir>/component/amqp/component.go:183 +0x20c
github.com/beatlabs/patron.(*service).run.func2(0xc000616000, 0xc000612000, 0xfdc960, 0xc00060e000, 0xfcbe20, 0xc0003d6000)
        <project_root_dir>/service.go:65 +0x77
created by github.com/beatlabs/patron.(*service).run
        <project_root_dir>/service.go:63 +0x1a3
```

The nil panic is triggered by dereferencing a nil string pointer in the following code location:

`client/sns/v2/publisher.go#72`  : `observePublish(span, start, *input.TopicArn, err)` where TopicArn is `nil`

## Describe the solution

Protect against panic and handle eventual errors/nil pointers.

I would like to receive some guidelines on what would be a good default behavior to protect the call to `observePublish(span, start, *input.TopicArn, err)` -> I can see 3 alternatives:

1. Skip the `observePublish` call altogether
    ```golang
    if input.TopicArn != nil {
        observePublish(span, start, *input.TopicArn, err)
    }
    ```
2. assign a default string in case `input.TopicArn` is null example below:
    ```golang
    var topicArn string
    if input.TopicArn != nil {
        topicArn = *input.TopicArn
    }
    observePublish(span, start, topicArn, err)
    ```
3. Return an error due to missing `TopicArn`:
    ```golang
    if input.TopicArn == nil {
        return "", fmt.Errorf("nil TopicArn - publication cannot be done")
    }
    ```
4. Observe `TargetArn` or `PhoneNumber` - in this case, which priority should we follow? My suggestion is to try to publish all that is availlable:
    ```golang
    if input.TopicArn != nil {
        observePublish(span, start, *input.TopicArn, err)
    }
    if input.TargetArn != nil {
        observePublish(span, start, *input.TargetArn, err)
    }
    ```
## Additional context

I have seen that no span is created for `PhoneNumber` should it be included in the discussion?

**Comment by rbroggi** [comment]
Fixed by PR #386
